version: '3.8'

services:
  db:
    image: postgres:13
    container_name: task_manager_db
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    ports:
      - "5432:5432"
    volumes:
      - taskmanager-db-data:/var/lib/postgresql/data
    networks:
      - taskmanager-network

  backend:
    image: openjdk:17-jdk
    container_name: task_manager_backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge

volumes:
  taskmanager-db-data:
